version: '3.8'

services:
  app:
    build: .
    deploy:
      replicas: 3
    networks:
      - loadbalance_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - loadbalance_net

networks:
  loadbalance_net:
    driver: bridge
